---
- name: Verify db container is present
  docker_container:
    name: postgres
    state: started
    image: "postgres:{{ postgres_version }}"
    volumes:
      - "{{ postgres_volume_path }}:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ postgres_username }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
  become: yes
  become_user: "{{ server_user }}"

- name: Verify database is present
  docker_container:
    name: postgres_db_create
    state: started
    image: "postgres:{{ postgres_version }}"
    links:
      - postgres:postgres
    command: "psql -c 'CREATE DATABASE blog;'"
  register: blog_database
  ignore_errors: yes
  become: yes
  become_user: "{{ server_user }}"

- debug:
    msg: "Docker database command output: {{ blog_database }} "

- name: Login into docker registry
  docker_login:
    registry: "registry.gitlab.com"
    username: "{{ blog_juanwolf_fr_registry_username }}"
    password: "{{ blog_juanwolf_fr_registry_password }}"
  become: yes
  become_user: "{{ server_user }}"

- name: "Recreate blog container with sentry url {{ sentry_host }}/{{ blog_juanwolf_fr_sentry_project_id }}"
  docker_container:
    name: "blog"
    image: "{{ blog_juanwolf_fr_image }}:{{ blog_juanwolf_fr_version }}"
    state: started
    recreate: yes
    pull: yes
    links:
      - "postgres:db"
      - "dd-agent:datadog"
    volumes:
      - "{{ blog_juanwolf_fr_volume_path  }}:/opt/juanwolf_fr/juanwolf_fr/media"
    published_ports:
      - "127.0.0.1:8000:8000"
    env:
      SECRET_KEY: "{{ blog_juanwolf_fr_secret_key }}"
      DATABASE_HOST: "db"
      DATABASE_NAME: "blog"
      DATABASE_USER: "{{ postgres_username }}"
      DATABASE_PASSWORD: "{{ postgres_password }}"
      SENTRY_PROTOCOL: "{{ sentry_protocol }}"
      SENTRY_USER: "{{ blog_juanwolf_fr_sentry_user  }}"
      SENTRY_PASSWORD: "{{ blog_juanwolf_fr_sentry_password }}"
      SENTRY_URL: "{{ sentry_host }}/{{ blog_juanwolf_fr_sentry_project_id }}"
      DATADOG_AGENT_HOSTNAME: "datadog"
  become: yes
  become_user: "{{ server_user }}"

- name: Run the migrations
  docker_container:
    name: "blog-tmp-container-exec"
    image: "{{ blog_juanwolf_fr_image }}:{{ blog_juanwolf_fr_version }}"
    command: /opt/virtualenvs/juanwolf_fr/bin/python manage.py migrate
    published_ports:
      - "11111:8000"
    links:
      - "postgres:db"
    env:
      SECRET_KEY: "{{ blog_juanwolf_fr_secret_key }}"
      DATABASE_HOST: "db"
      DATABASE_NAME: "blog"
      DATABASE_USER: "{{ postgres_username }}"
      DATABASE_PASSWORD: "{{ postgres_password }}"
  become: yes
  become_user: "{{ server_user }}"

- name: Destroy tmp container
  docker_container:
    name: "blog-tmp-container-exec"
    state: absent
  become: yes
  become_user: "{{ server_user }}"

